### ISSUE TITLE
Baoefeng DM-1801 How to flash back to factory FW

### ISSUE THREAD

**Issue by PD5JOS** [rogerclarkmelbourne/Radioddity_GD-77#59]
Hello Roger,

I have here a Baofeng DM-1801 with has from factory a problem with the DMR sound. The DMR sound is like im sitting in a chopper. We have 50% ratchet and 50% voice. The offset for RX and TX are fine and in FM mode there is no problem. I run into the your open GD77 FW and flashed that into my 1801. Looks very need and good, better then the Baofeng FW. But we have still the same problem in DMR.  I only can come to the conclusion that this is a defect DM-1801. I already opened a dispute and i think i have to sent the MD-1801 back soon.

My problem now is when i flash the Original version DM-1801_v2.1.9.sql or BF-1801_V2.2.5.sql back i got an "low BT version" on my screen, and the 1801 wont boot. Q: How can i flash the Original FW without this error and have a starting 1801 again.

Thanks, PD5JOS

**Comment by rogerclarkmelbourne** [comment]
This is not a good sign.

Some part of the MCU ROM is corrupt.

Did you backup your MCU ROM using the OpenGD77 CPS ?
https://github.com/rogerclarkmelbourne/OpenGD77CPS/releases/

If not. 

Reload the OpenDM1801, backup the MCU ROM, then zip the bin file and post it here.

You may not be able to reload any firmware at all if the ROM is completely corrupt, in which case the MCU would need to be reflashed by connecting directly inside the radio.

BTW. The bug of "50% ratchet and 50% voice" may just be caused by bad calibration in the radio and not actually be a hardware fault, But a hardware fault is probably more likely

**Comment by rogerclarkmelbourne** [comment]
BTW.

You could try loading one of @forkoz's versions of the DM-1801 firmware

See

https://github.com/rogerclarkmelbourne/Radioddity_GD-77/issues/41

I think in the modified firmware by @forkoz , he removed some things which can cause that message even if the ROM has some corruption

**Comment by PD5JOS** [comment]
Hello Roger,

Thanks for the quick reply. Somehow i managed to get back to the old FW already now (before your answerd) I start testing again, and i think the problem is in my DVMega Hotspot. 

So thanks again, wil see what i do whit this port, Have received also my Anytone 878UV now and is wirking great.

You may close this # for me
'73 PD5JOS

**Comment by rogerclarkmelbourne** [comment]
Ok
